"use client";

import { useCallback, useEffect, useState } from "react";
import { ModuleFrame, ModuleTabs } from "@/components/ModuleFrame";
import { MonthInput } from "@/components/DateInput";
import { branchScopeOptions, storeLabel, storeOptions } from "@/lib/branch-labels";
import { canPerformMenuAction } from "@/lib/auth-demo";
import { useModuleAuth } from "@/lib/use-module-auth";

type Pnl = { revenue: number; cogs: number; payroll: number; depreciation: number; otherOpex: number; otherIncome: number; otherExpense: number; grossProfit: number; opexBeforeDepreciation: number; ebitda: number; operatingProfit: number; netProfit: number; grossMargin: number; ebitdaMargin: number };
type PnlCut = Pnl & { code: string };
type DashboardData = { pnl: { total: Pnl; byBranch: PnlCut[] }; trend: Array<Pnl & { period: string }>; balance: BalanceData; targets: Array<{ metric: string; targetValue: number }> };
type PnlData = { total: Pnl; byBranch: PnlCut[]; byDepartment: PnlCut[] };
type YoyData = { previousPeriod: string; rows: Array<{ metric: string; currentValue: number; previousValue: number; variance: number; varianceRate: number | null }> };
type CashflowData = { scenario: string; startingCash: number; schedule: Array<{ period: string; inflow: number; outflow: number; closingCash: number; risk: boolean }> };
type BalanceRow = { code: string; name: string; accountType: string; reportGroup: string; amount: number };
type BalanceData = { rows: BalanceRow[]; assets: number; liabilities: number; contributedEquity: number; retainedEarnings: number; equity: number; difference: number; balanced: boolean };
const money = (value: number) => new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 0 }).format(value);
const metricLabels: Record<string, string> = { revenue: "Doanh thu", cogs: "Giá vốn", grossProfit: "Lợi nhuận gộp", opexBeforeDepreciation: "OPEX trước khấu hao", ebitda: "EBITDA", netProfit: "Lợi nhuận ròng" };

export default function ReportsPage() {
  const href = "/reports";
  const { user, loading } = useModuleAuth(href);
  const [active, setActive] = useState("dashboard");
  const [period, setPeriod] = useState(new Date().toISOString().slice(0, 7));
  const [branchCode, setBranchCode] = useState("ALL");
  const [scenario, setScenario] = useState("BASE");
  const [data, setData] = useState<DashboardData | PnlData | YoyData | CashflowData | BalanceData | null>(null);
  const [message, setMessage] = useState("");
  const [forecast, setForecast] = useState({ period: new Date().toISOString().slice(0, 7), branchCode: "HCM", scenario: "BASE", assumptionType: "INFLOW", amount: "100000000", note: "Kế hoạch dòng tiền" });
  const canConfigure = user ? canPerformMenuAction(user.role, href, "create") : false;

  useEffect(() => {
    const tab = new URLSearchParams(window.location.search).get("tab");
    if (tab && ["dashboard", "pnl", "yoy", "cashflow", "balance"].includes(tab)) window.setTimeout(() => setActive(tab), 0);
  }, []);

  const loadData = useCallback(async () => {
    const response = await fetch(`/api/reports?type=${active}&period=${period}&branchCode=${branchCode}&scenario=${scenario}`);
    if (response.ok) setData(await response.json());
  }, [active, branchCode, period, scenario]);
  useEffect(() => { if (!loading) window.setTimeout(() => void loadData(), 0); }, [loading, loadData]);
  const saveForecast = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch("/api/reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "UPSERT_FORECAST", ...forecast }) }); const payload = await response.json(); setMessage(response.ok ? "Đã lưu giả định dự báo." : payload.error || "Không lưu được giả định"); if (response.ok) await loadData(); };
  if (loading) return <div className="h-screen grid place-items-center bg-slate-100">Đang tải...</div>;
  const dashboard = active === "dashboard" ? data as DashboardData | null : null;
  const pnl = active === "pnl" ? data as PnlData | null : null;
  const yoy = active === "yoy" ? data as YoyData | null : null;
  const cashflow = active === "cashflow" ? data as CashflowData | null : null;
  const balance = active === "balance" ? data as BalanceData | null : null;
  return <ModuleFrame title="Báo cáo & BI" subtitle="GĐ4 - Dashboard, P&L, YoY, dự báo dòng tiền và bảng cân đối" role={user?.role}>
    <div className="flex flex-wrap items-end gap-3 mb-4"><Field label="Kỳ báo cáo"><MonthInput className="mt-1.5 w-40" value={period} onChange={setPeriod} ariaLabel="Kỳ báo cáo" /></Field><Field label="Phạm vi cửa hàng"><select className="control w-56" value={branchCode} onChange={(e) => setBranchCode(e.target.value)}>{branchScopeOptions.map((option) => <option key={option.code} value={option.code}>{option.label}</option>)}</select></Field>{active === "cashflow" && <Field label="Kịch bản"><select className="control w-40" value={scenario} onChange={(e) => setScenario(e.target.value)}><option value="BASE">Cơ sở</option><option value="UPSIDE">Tích cực</option><option value="DOWNSIDE">Thận trọng</option></select></Field>}<button type="button" className="icon-button" title="Tải lại" onClick={() => void loadData()}><span className="material-symbols-outlined text-lg">refresh</span></button></div>
    <ModuleTabs active={active} onChange={setActive} tabs={[{ id: "dashboard", label: "Điều hành", icon: "dashboard" }, { id: "pnl", label: "P&L đa chiều", icon: "finance" }, { id: "yoy", label: "Biến động YoY", icon: "query_stats" }, { id: "cashflow", label: "Dự báo dòng tiền", icon: "timeline" }, { id: "balance", label: "Bảng cân đối", icon: "account_balance" }]} />
    {message && <p className="mb-4 px-4 py-3 rounded-lg border border-blue-100 bg-blue-50 text-sm text-blue-700">{message}</p>}

    {dashboard && <div className="space-y-5"><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Kpi label="Doanh thu" value={dashboard.pnl.total.revenue} icon="payments" /><Kpi label="Lợi nhuận gộp" value={dashboard.pnl.total.grossProfit} icon="trending_up" tone="green" /><Kpi label="EBITDA" value={dashboard.pnl.total.ebitda} icon="monitoring" tone="blue" /><Kpi label="Tiền hiện có" value={dashboard.balance.rows.filter((row) => row.reportGroup === "CASH").reduce((sum, row) => sum + row.amount, 0)} icon="account_balance_wallet" tone="amber" /></div><div className="grid xl:grid-cols-[1.4fr_1fr] gap-5"><section className="bg-white border border-slate-200 rounded-lg p-5"><h2 className="font-bold">Xu hướng 6 tháng</h2><p className="text-xs text-slate-500 mt-1">Doanh thu và EBITDA từ dữ liệu đã ghi sổ.</p><div className="mt-6 space-y-4">{dashboard.trend.map((row) => { const max = Math.max(...dashboard.trend.map((item) => Math.abs(item.revenue)), 1); return <div key={row.period} className="grid grid-cols-[70px_1fr_120px] gap-3 items-center text-sm"><b>{row.period}</b><div className="h-6 bg-slate-100 rounded overflow-hidden"><div className="h-full bg-blue-600" style={{ width: `${Math.max(2, Math.abs(row.revenue) / max * 100)}%` }} /></div><span className="text-right font-bold">{money(row.revenue)} đ</span></div>; })}</div></section><section className="bg-white border border-slate-200 rounded-lg p-5"><h2 className="font-bold">Hiệu quả theo cửa hàng</h2><div className="mt-4 divide-y divide-slate-100">{dashboard.pnl.byBranch.length === 0 ? <p className="py-8 text-center text-sm text-slate-400">Chưa có dữ liệu ghi sổ.</p> : dashboard.pnl.byBranch.map((row) => <div key={row.code} className="py-3 flex justify-between gap-3"><div><b>{storeLabel(row.code)}</b><p className="text-xs text-slate-500 mt-1">Biên gộp {(row.grossMargin * 100).toFixed(1)}%</p></div><div className="text-right"><b>{money(row.revenue)} đ</b><p className={`text-xs mt-1 ${row.ebitda >= 0 ? "text-emerald-600" : "text-rose-600"}`}>EBITDA {money(row.ebitda)} đ</p></div></div>)}</div></section></div></div>}

    {pnl && <div className="space-y-5"><section className="bg-white border border-slate-200 rounded-lg overflow-hidden"><div className="p-5"><h2 className="font-bold">Báo cáo Kết quả Kinh doanh</h2><p className="text-xs text-slate-500 mt-1">Đơn vị: VND</p></div><PnlTable value={pnl.total} /></section><div className="grid xl:grid-cols-2 gap-5"><CutTable title="Theo cửa hàng" rows={pnl.byBranch} /><CutTable title="Theo phòng ban" rows={pnl.byDepartment} /></div></div>}

    {yoy && <section className="table-panel"><div className="p-5"><h2 className="font-bold">So sánh {period} với {yoy.previousPeriod}</h2><p className="text-xs text-slate-500 mt-1">Chỉ hiển thị tỷ lệ khi kỳ trước có dữ liệu.</p></div><Table headers={["Chỉ tiêu", period, yoy.previousPeriod, "Chênh lệch", "Tỷ lệ"]}>{yoy.rows.map((row) => <tr key={row.metric} className="border-t border-slate-100"><Cell><b>{metricLabels[row.metric] || row.metric}</b></Cell><Cell right>{money(row.currentValue)} đ</Cell><Cell right>{money(row.previousValue)} đ</Cell><Cell right><span className={row.variance >= 0 ? "text-emerald-700" : "text-rose-700"}>{money(row.variance)} đ</span></Cell><Cell right>{row.varianceRate === null ? "Thiếu dữ liệu" : `${(row.varianceRate * 100).toFixed(1)}%`}</Cell></tr>)}</Table></section>}

    {cashflow && <div className="grid xl:grid-cols-[360px_1fr] gap-5">{canConfigure && <form onSubmit={saveForecast} className="bg-white border border-slate-200 rounded-lg p-5 space-y-4 h-fit"><h2 className="font-bold">Giả định dòng tiền</h2><Field label="Kỳ dự kiến"><MonthInput className="mt-1.5" value={forecast.period} onChange={(period) => setForecast({ ...forecast, period })} ariaLabel="Kỳ dự kiến" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Cửa hàng"><select className="control" value={forecast.branchCode} onChange={(e) => setForecast({ ...forecast, branchCode: e.target.value })}>{storeOptions.map((option) => <option key={option.code} value={option.code}>{storeLabel(option.code)}</option>)}</select></Field><Field label="Kịch bản"><select className="control" value={forecast.scenario} onChange={(e) => setForecast({ ...forecast, scenario: e.target.value })}><option value="BASE">Cơ sở</option><option value="UPSIDE">Tích cực</option><option value="DOWNSIDE">Thận trọng</option></select></Field></div><Field label="Loại"><select className="control" value={forecast.assumptionType} onChange={(e) => setForecast({ ...forecast, assumptionType: e.target.value })}><option value="INFLOW">Dòng tiền vào</option><option value="OUTFLOW">Dòng tiền ra</option></select></Field><Field label="Số tiền"><input type="number" className="control" value={forecast.amount} onChange={(e) => setForecast({ ...forecast, amount: e.target.value })} /></Field><Field label="Ghi chú"><textarea className="control h-20 resize-none" value={forecast.note} onChange={(e) => setForecast({ ...forecast, note: e.target.value })} /></Field><button className="primary-button w-full">Lưu giả định</button></form>}<section className="table-panel"><div className="p-5 flex justify-between"><div><h2 className="font-bold">Dự báo 3 tháng - {cashflow.scenario}</h2><p className="text-xs text-slate-500 mt-1">Số dư bắt đầu: {money(cashflow.startingCash)} đ</p></div></div><Table headers={["Kỳ", "Dòng tiền vào", "Dòng tiền ra", "Số dư dự kiến", "Cảnh báo"]}>{cashflow.schedule.map((row) => <tr key={row.period} className="border-t border-slate-100"><Cell><b>{row.period}</b></Cell><Cell right className="text-emerald-700">{money(row.inflow)} đ</Cell><Cell right className="text-rose-700">{money(row.outflow)} đ</Cell><Cell right><b>{money(row.closingCash)} đ</b></Cell><Cell>{row.risk ? <span className="status bg-rose-50 text-rose-700">Thiếu tiền</span> : <span className="status bg-emerald-50 text-emerald-700">An toàn</span>}</Cell></tr>)}</Table></section></div>}

    {balance && <div className="space-y-5"><div className="grid sm:grid-cols-3 gap-4"><Kpi label="Tổng tài sản" value={balance.assets} icon="apartment" /><Kpi label="Nợ phải trả" value={balance.liabilities} icon="credit_card" tone="amber" /><Kpi label="Vốn chủ sở hữu" value={balance.equity} icon="savings" tone="green" /></div><section className="table-panel"><div className="p-5 flex items-center justify-between"><div><h2 className="font-bold">Phân tích Bảng cân đối</h2><p className="text-xs text-slate-500 mt-1">Lợi nhuận lũy kế: {money(balance.retainedEarnings)} đ</p></div><span className={`status ${balance.balanced ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{balance.balanced ? "CÂN" : `LỆCH ${money(balance.difference)} đ`}</span></div><Table headers={["Tài khoản", "Tên", "Nhóm", "Loại", "Số dư"]}>{balance.rows.map((row) => <tr key={row.code} className="border-t border-slate-100"><Cell><b>{row.code}</b></Cell><Cell>{row.name}</Cell><Cell>{row.reportGroup}</Cell><Cell>{row.accountType}</Cell><Cell right><b>{money(row.amount)} đ</b></Cell></tr>)}</Table></section></div>}
  </ModuleFrame>;
}

function Kpi({ label, value, icon, tone = "slate" }: { label: string; value: number; icon: string; tone?: "slate" | "green" | "blue" | "amber" }) { const style = tone === "green" ? "bg-emerald-50 text-emerald-600" : tone === "blue" ? "bg-blue-50 text-blue-600" : tone === "amber" ? "bg-amber-50 text-amber-600" : "bg-slate-100 text-slate-600"; return <div className="bg-white border border-slate-200 rounded-lg p-4 flex items-center gap-3"><div className={`h-11 w-11 rounded-lg grid place-items-center ${style}`}><span className="material-symbols-outlined">{icon}</span></div><div><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-bold mt-1">{money(value)} đ</p></div></div>; }
function PnlTable({ value }: { value: Pnl }) { const rows = [["Doanh thu", value.revenue], ["Giá vốn", -value.cogs], ["Lợi nhuận gộp", value.grossProfit], ["Chi phí nhân sự", -value.payroll], ["OPEX khác", -value.otherOpex], ["EBITDA", value.ebitda], ["Khấu hao", -value.depreciation], ["Lợi nhuận hoạt động", value.operatingProfit], ["Thu nhập khác", value.otherIncome], ["Lợi nhuận ròng", value.netProfit]] as const; return <div className="divide-y divide-slate-100">{rows.map(([label, amount]) => <div key={label} className={`px-5 py-3 flex justify-between ${["Lợi nhuận gộp", "EBITDA", "Lợi nhuận ròng"].includes(label) ? "bg-slate-50 font-bold" : ""}`}><span>{label}</span><span className={amount < 0 ? "text-rose-700" : ""}>{money(amount)} đ</span></div>)}</div>; }
function CutTable({ title, rows }: { title: string; rows: PnlCut[] }) { return <section className="table-panel"><div className="p-5"><h2 className="font-bold">{title}</h2></div><Table headers={["Đơn vị", "Doanh thu", "Lợi nhuận gộp", "EBITDA"]}>{rows.map((row) => <tr key={row.code} className="border-t border-slate-100"><Cell><b>{storeLabel(row.code)}</b></Cell><Cell right>{money(row.revenue)} đ</Cell><Cell right>{money(row.grossProfit)} đ</Cell><Cell right>{money(row.ebitda)} đ</Cell></tr>)}</Table></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-bold text-slate-600">{label}{children}</label>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500 uppercase"><tr>{headers.map((header) => <th key={header} className="px-4 py-3 text-left last:text-right">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Cell({ children, right = false, className = "" }: { children: React.ReactNode; right?: boolean; className?: string }) { return <td className={`cell ${right ? "text-right" : ""} ${className}`}>{children}</td>; }
