"use client";

import { useCallback, useEffect, useState } from "react";
import { ModuleFrame } from "@/components/ModuleFrame";
import { DateInput, MonthInput } from "@/components/DateInput";
import { storeLabel, storeOptions } from "@/lib/branch-labels";
import { canPerformMenuAction } from "@/lib/auth-demo";
import { useModuleAuth } from "@/lib/use-module-auth";

type WorkItem = { id: string; code: string; title: string; description: string | null; branchCode: string; departmentCode: string; assigneeName: string; priority: string; status: string; dueDate: string; createdBy: string | null; isOverdue: boolean };
type Data = { items: WorkItem[]; summary: { total: number; completed: number; overdue: number; waitingApproval: number } };
const statusLabels: Record<string, string> = { TODO: "Chưa làm", IN_PROGRESS: "Đang làm", WAITING_APPROVAL: "Chờ duyệt", COMPLETED: "Hoàn thành", CANCELLED: "Đã hủy" };

export default function WorkManagementPage() {
  const href = "/work-management";
  const { user, loading } = useModuleAuth(href);
  const [data, setData] = useState<Data>({ items: [], summary: { total: 0, completed: 0, overdue: 0, waitingApproval: 0 } });
  const [status, setStatus] = useState("ALL");
  const [message, setMessage] = useState("");
  const [form, setForm] = useState({ title: "Đối chiếu số liệu cuối tháng", description: "Kiểm tra chứng từ và hoàn tất checklist", branchCode: "HCM", departmentCode: "ACCOUNTING", assigneeName: "Kế toán phụ trách", priority: "HIGH", period: new Date().toISOString().slice(0, 7), dueDate: new Date().toISOString().slice(0, 10) });
  const canCreate = user ? canPerformMenuAction(user.role, href, "create") : false;
  const canEdit = user ? canPerformMenuAction(user.role, href, "edit") : false;
  const canApprove = user ? canPerformMenuAction(user.role, href, "approve") : false;
  const loadData = useCallback(async () => { const response = await fetch(`/api/work-management?status=${status}`); if (response.ok) setData(await response.json() as Data); }, [status]);
  useEffect(() => { if (!loading) window.setTimeout(() => void loadData(), 0); }, [loading, loadData]);
  const send = async (method: "POST" | "PATCH", body: object, success: string) => { const response = await fetch("/api/work-management", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); setMessage(response.ok ? success : payload.error || "Không thực hiện được thao tác"); if (response.ok) await loadData(); };
  if (loading) return <div className="h-screen grid place-items-center bg-slate-100">Đang tải...</div>;
  return <ModuleFrame title="Phân bổ & Tiến độ Công việc" subtitle="GĐ4 - Nhóm G 7.1–7.2" role={user?.role}>
    <div className="grid sm:grid-cols-4 gap-4 mb-5"><Metric label="Tổng công việc" value={data.summary.total} icon="assignment" /><Metric label="Hoàn thành" value={data.summary.completed} icon="check_circle" tone="green" /><Metric label="Chờ duyệt" value={data.summary.waitingApproval} icon="approval" tone="blue" /><Metric label="Quá hạn" value={data.summary.overdue} icon="warning" tone="red" /></div>
    {message && <p className="mb-4 px-4 py-3 rounded-lg border border-blue-100 bg-blue-50 text-sm text-blue-700">{message}</p>}
    <div className="grid xl:grid-cols-[380px_1fr] gap-5">{canCreate && <form onSubmit={(e) => { e.preventDefault(); void send("POST", form, "Đã phân bổ công việc."); }} className="bg-white border border-slate-200 rounded-lg p-5 space-y-4 h-fit"><h2 className="font-bold">Phân bổ công việc</h2><Field label="Tiêu đề"><input className="control" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label="Mô tả"><textarea className="control h-20 resize-none" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Cửa hàng"><select className="control" value={form.branchCode} onChange={(e) => setForm({ ...form, branchCode: e.target.value })}>{storeOptions.map((option) => <option key={option.code} value={option.code}>{storeLabel(option.code)}</option>)}</select></Field><Field label="Phòng ban"><input data-input-kind="code" className="control" value={form.departmentCode} onChange={(e) => setForm({ ...form, departmentCode: e.target.value })} /></Field></div><Field label="Người phụ trách"><input className="control" value={form.assigneeName} onChange={(e) => setForm({ ...form, assigneeName: e.target.value })} /></Field><div className="grid grid-cols-3 gap-3"><Field label="Ưu tiên"><select className="control" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="LOW">Thấp</option><option value="MEDIUM">Trung bình</option><option value="HIGH">Cao</option></select></Field><Field label="Kỳ"><MonthInput className="mt-1.5" value={form.period} onChange={(period) => setForm({ ...form, period })} ariaLabel="Kỳ công việc" /></Field><Field label="Hạn"><DateInput className="mt-1.5" value={form.dueDate} onChange={(dueDate) => setForm({ ...form, dueDate })} ariaLabel="Hạn công việc" /></Field></div><button className="primary-button w-full"><span className="material-symbols-outlined text-lg">add_task</span>Tạo công việc</button></form>}
      <section className="table-panel"><div className="p-5 flex items-center justify-between gap-3"><div><h2 className="font-bold">Theo dõi tiến độ</h2><p className="text-xs text-slate-500 mt-1">Công việc quá hạn được đánh dấu theo ngày hiện tại.</p></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="border border-slate-300 rounded-lg px-3 py-2 text-sm"><option value="ALL">Tất cả</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="divide-y divide-slate-100">{data.items.length === 0 ? <p className="p-10 text-center text-sm text-slate-400">Chưa có công việc.</p> : data.items.map((item) => <article key={item.id} className="p-4 hover:bg-slate-50"><div className="flex flex-wrap items-start gap-3"><div className={`h-10 w-10 rounded-lg grid place-items-center ${item.isOverdue ? "bg-rose-50 text-rose-600" : "bg-slate-100 text-slate-600"}`}><span className="material-symbols-outlined">{item.isOverdue ? "schedule" : "task"}</span></div><div className="flex-1 min-w-52"><div className="flex flex-wrap gap-2 items-center"><b>{item.code} - {item.title}</b><span className="status bg-slate-100">{item.priority}</span><span className={`status ${item.status === "COMPLETED" ? "bg-emerald-50 text-emerald-700" : item.status === "WAITING_APPROVAL" ? "bg-blue-50 text-blue-700" : "bg-amber-50 text-amber-700"}`}>{statusLabels[item.status]}</span></div><p className="text-sm text-slate-600 mt-1">{item.description || "-"}</p><p className="text-xs text-slate-500 mt-2">{storeLabel(item.branchCode)} · {item.departmentCode} · {item.assigneeName} · Hạn {new Date(item.dueDate).toLocaleDateString("vi-VN")}</p></div><div className="flex gap-2">{canEdit && item.status === "TODO" && <button onClick={() => void send("PATCH", { id: item.id, status: "IN_PROGRESS" }, "Đã bắt đầu công việc.")} className="secondary-button">Bắt đầu</button>}{canEdit && item.status === "IN_PROGRESS" && <button onClick={() => void send("PATCH", { id: item.id, status: "WAITING_APPROVAL" }, "Đã gửi duyệt hoàn thành.")} className="primary-button">Gửi duyệt</button>}{canApprove && item.status === "WAITING_APPROVAL" && <button onClick={() => void send("PATCH", { action: "APPROVE", id: item.id }, "Đã duyệt hoàn thành.")} className="primary-button">Duyệt</button>}</div></div></article>)}</div></section>
    </div>
  </ModuleFrame>;
}
function Metric({ label, value, icon, tone = "slate" }: { label: string; value: number; icon: string; tone?: "slate" | "green" | "blue" | "red" }) { const color = tone === "green" ? "text-emerald-600 bg-emerald-50" : tone === "blue" ? "text-blue-600 bg-blue-50" : tone === "red" ? "text-rose-600 bg-rose-50" : "text-slate-600 bg-slate-100"; return <div className="bg-white border border-slate-200 rounded-lg p-4 flex items-center gap-3"><div className={`h-10 w-10 rounded-lg grid place-items-center ${color}`}><span className="material-symbols-outlined">{icon}</span></div><div><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold">{value}</p></div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-bold text-slate-600">{label}{children}</label>; }
