-- Keep the generated customer-deposit record traceable to its opening balance.
ALTER TABLE "Deposit" ADD COLUMN "sourceOpeningBalanceId" TEXT;

CREATE UNIQUE INDEX "Deposit_sourceOpeningBalanceId_key"
ON "Deposit"("sourceOpeningBalanceId");

ALTER TABLE "Deposit"
ADD CONSTRAINT "Deposit_sourceOpeningBalanceId_fkey"
FOREIGN KEY ("sourceOpeningBalanceId") REFERENCES "OpeningBalance"("id")
ON DELETE SET NULL ON UPDATE CASCADE;

-- Link deposits generated by the former import implementation when their legacy code matches.
UPDATE "Deposit" AS deposit
SET "sourceOpeningBalanceId" = opening.id
FROM "OpeningBalance" AS opening
WHERE opening."balanceType" = 'DEPOSIT'
  AND opening."deletedAt" IS NULL
  AND deposit."deletedAt" IS NULL
  AND deposit."sourceOpeningBalanceId" IS NULL
  AND deposit.code = CONCAT('COC-DK-', REPLACE(opening.period, '-', ''), '-', opening."branchCode", '-', opening."objectCode")
  AND NOT EXISTS (
    SELECT 1 FROM "Deposit" AS linked
    WHERE linked."sourceOpeningBalanceId" = opening.id
  );

-- Materialize manual confirmed opening deposits that previously never reached the deposit ledger.
WITH inserted AS (
  INSERT INTO "Deposit" (
    "id", "code", "receivedDate", "partnerCode", "partnerName", "branchCode",
    "moneySourceCode", "amount", "remainingAmount", "purpose", "status", "note",
    "sourceOpeningBalanceId", "createdAt", "updatedAt"
  )
  SELECT
    md5(random()::text || clock_timestamp()::text)::uuid::text,
    CONCAT('COC-DK-', REPLACE(opening.period, '-', ''), '-', UPPER(SUBSTRING(opening.id, 1, 8))),
    (opening.period || '-01')::date,
    opening."objectCode",
    COALESCE(opening."objectName", opening."objectCode"),
    opening."branchCode",
    opening."moneySourceCode",
    opening.amount,
    opening.amount,
    'Tiền cọc đầu kỳ',
    'HOLDING',
    opening.note,
    opening.id,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  FROM "OpeningBalance" AS opening
  WHERE opening."balanceType" = 'DEPOSIT'
    AND opening.status IN ('POSTED', 'CONFIRMED')
    AND opening."deletedAt" IS NULL
    AND opening."objectCode" IS NOT NULL
    AND opening."moneySourceCode" IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM "Deposit" AS deposit
      WHERE deposit."sourceOpeningBalanceId" = opening.id
    )
  RETURNING id, "sourceOpeningBalanceId", amount, "receivedDate", "createdAt"
)
INSERT INTO "DepositHistory" (
  "id", "depositId", "action", "amount", "actionDate", "treatmentNote", "actor", "createdAt"
)
SELECT md5(random()::text || clock_timestamp()::text)::uuid::text, id, 'OPENING', amount, "receivedDate", 'Số dư tiền cọc đầu kỳ', 'MIGRATION', "createdAt"
FROM inserted;

-- Canonical retail customer used for deposits that do not belong to a named customer.
INSERT INTO "MasterDataItem" (
  "id", "type", "code", "name", "group", "partnerType", "partnerGroup",
  "status", "note", "createdAt", "updatedAt"
)
VALUES (
  '00000000-0000-4000-8000-00000000c001',
  'PARTNER', 'KH_LE', 'Khách hàng mua lẻ', 'CUSTOMER', 'CUSTOMER', 'EXTERNAL',
  'ACTIVE', 'Đối tượng mặc định cho tiền cọc khách lẻ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
ON CONFLICT ("type", "code") DO UPDATE SET
  "name" = EXCLUDED."name",
  "group" = EXCLUDED."group",
  "partnerType" = EXCLUDED."partnerType",
  "partnerGroup" = EXCLUDED."partnerGroup",
  "status" = 'ACTIVE',
  "deletedAt" = NULL,
  "deletedBy" = NULL,
  "updatedAt" = CURRENT_TIMESTAMP;
